global:
  resolve_timeout: 5m

templates:
- '/etc/prometheus/alertmanager_templates/*.tmpl'

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 30m
  receiver: 'slack-alerts'
  match:
    severity: 'critical'
  # A default receiver

receivers:
  - name: 'slack-alerts'
    slack_configs:
      - slack_api_url:  https://hooks.slack.com
      - channel: '#test-alerts'
        send_resolved:  true
        title:
